name: "gh-large-releases"
author: "ading2210"
description: "Upload files larger than 2GB to GitHub Releases"

inputs:
  repository:
    description: "Repository to make releases against, in <owner>/<repo> format."
    required: false
    default: ${{ github.repository }}
  files:
    description: "A list of files to upload to the release."
    required: true
  token:
    description: "The GitHub access token to use."
    required: false
    default: ${{ github.token }}
  workspace:
    description: "The path to the default working directory."
    required: false
    default: ${{ github.workspace }}
  worker_url:
    description: "Override the URL to the Cloudflare Worker that serves the release files."
    required: false
  
  tag_name:
    description: "The name of the tag."
    required: false
  target_commitish:
    description: "Specifies the commitish value that determines where the Git tag is created from."
    required: false
  name:
    description: "The name of the release."
    required: false
  body:
    description: "Text describing the contents of the tag."
    required: false
  draft:
    description: "`true` to create a draft (unpublished) release, `false` to create a published one."
    required: false
  prerelease:
    description: "`true` to identify the release as a prerelease. `false` to identify the release as a full release."
    required: false
  make_latest:
    description: "Specifies whether this release should be set as the latest release for the repository."
    required: false
  generate_release_notes:
    description: "Whether to automatically generate the name and body for this release."
    required: false
  discussion_category_name:
    description: "If specified, a discussion of the specified category is created and linked to the release."
    required: false

runs:
  using: "composite"
  steps:
    - name: run main
      shell: bash
      run: |
        cd ${{ github.action_path }}
        python3 -m venv .venv
        source .venv/bin/activate
        pip3 install -r requirements.txt
        python3 action/main.py \
          --repository='{{ inputs.repository }}' \
          --files='${{ inputs.files }}' \
          --token='${{ inputs.token }}' \
          --workspace='${{ inputs.workspace }}' \
          --tag_name='${{ inputs.tag_name }}' \
          --target_commitish='${{ inputs.target_commitish }}' \
          --name='${{ inputs.name }}' \
          --body='${{ inputs.body }}' \
          --draft='${{ inputs.draft }}' \
          --prerelease='${{ inputs.prerelease }}' \
          --make_latest='${{ inputs.make_latest }}' \
          --generate_release_notes='${{ inputs.generate_release_notes }}' \
          --discussion_category_name='${{ inputs.discussion_category_name }}' 

branding:
  color: "green"
  icon: "package"